### ISSUE TITLE
hardware: Window move, minimise and restore

### ISSUE THREAD

**Issue by R0CKH0PP3R** [linuxmint/lmde-5-cinnamon-beta#10] opened 2022-03-01 16:59 UTC
**Issue**
When only a single window is displayed it becomes glitchy after being moved, minimised and restored. The issue isn't unique to 21:9 resolutions or the Nvidia driver - the same behaviour also occurs on my Intel laptop. The issue was previously reported against Cinnamon 2 years ago but gained no interest: https://github.com/linuxmint/cinnamon/issues/9216 - a video showing the issue is linked there.

**Steps to reproduce**
Open a single window. e.g. Nemo.
Move it to the right.
Minimise it.
Restore it.
Place mouse cursor over restored window.

**Expected behaviour**
I would expect it to behave as it did before the window was moved to the side.

**Other information**
All settings were at defaults, running from the LMDE5 Beta live media.

**Comment by Secret-chest** [comment] 2022-03-01 17:05
Cannot repro (LM 20.3)

**Comment by Ethanol6** [comment] 2022-03-02 02:36
VM? Bare Metal? Does it persist after installation?

**Comment by R0CKH0PP3R** [comment] 2022-03-02 09:29
Bare metal: Ryzen 3600 with Nvidia 1070. Not installed LMDE5 but it did persist after installing Mint 19.3 & LMDE4. As mentioned in my related Cinnamon bug report, the issue was also present on my Intel laptop (pentium N4200).

Edit: Also tested on a Virtualbox VM and get the same result. So, live, installed, bare metal, VM, AMD, intel & Nvidia, all affected over multiple releases.

**Comment by R0CKH0PP3R** [comment] 2022-03-02 18:30
To note: Debian 11.2 does not display this issue when running the debian-live-11.2.0-amd64-cinnamon iso (VM or bare metal).

**Comment by lumixdeee** [comment] 2022-03-02 18:45
Cannot reproduce on AMD64 lmde4 running mate desktop with nemo, marco

**Comment by Ethanol6** [comment] 2022-03-03 05:17
I cannot reproduce this on KVM/QEMU Live or installed.

Did you verify the ISO?

Have you tried running Cinnamon in "Software Rendering" mode?

In your video I see mouse artifacts at the 20 second mark. Before you move the window. Do you see this or is it a product of the screen recording?

**Comment by R0CKH0PP3R** [comment] 2022-03-03 07:26
> I cannot reproduce this on KVM/QEMU Live or installed.
> 
> Did you verify the ISO?
> 
> Have you tried running Cinnamon in "Software Rendering" mode?
> 
> In your video I see mouse artifacts at the 20 second mark. Before you move the window. Do you see this or is it a product of the screen recording?

I verified the iso.
I have not tried running in software rendering mode.
The mouse artifacts are a product of the recording - thank you for spending the time to watch it.

**Comment by R0CKH0PP3R** [comment] 2022-03-03 15:46
To note: Disabling Window effects appears to circumvent the issue.

**Comment by C8forT** [comment] 2022-03-04 00:37
Cannot reproduce on LMDE 5 nor Linux Mint Cinnamon 20.3.

**Comment by clefebvre** [comment] 2022-03-11 16:24
I'll close this since it doesn't lead to a bug fix resolution. It looks like a hardware support issue, I'd suggest troubleshooting it on the forums.

**Closed as completed by clefebvre** 2022-03-11 16:24 UTC

**Comment by R0CKH0PP3R** [comment] 2022-03-11 19:30
So I tell you that it occurs on both a Ryzen desktop with Nvidia gfx and an Intel laptop, both on bare metal and a VM, while it's limited to window effects and that it doesn't occur on Debian, and you're telling me it's my hardware? I really was hoping that you'd get this sorted after 2 years but I guess I'll look elsewhere now.
