### ISSUE TITLE
Error tryuing to resize screen in LMDE 5 running on virtual machine

### ISSUE THREAD

**Issue by kangal3632** [linuxmint/lmde-5-cinnamon-beta#21] opened 2022-03-03 08:16 UTC
When I try to adjust the display resolution from the recommended 1024 X 768, an error window pops up saying: failed to apply configuration. One this error occurs, the only recourse I have is to force shutdown and then reopen LMDE 5
![Screenshot from 2022-03-03 10-43-50](https://user-images.githubusercontent.com/100831976/156524064-8ab3762c-bb6c-45cb-8335-91bdadfb49f1.png)

**Comment by xenopeek** [comment] 2022-03-03 08:45
You're doing this on Gnome Boxes I think? I tried the same and setting a different resolution works I get the same error. But I can click "Close" at the bottom of the error window and it goes away and the virtual machine works fine afterwards (on the new resolution). You can't click Close?

**Comment by xenopeek** [comment] 2022-03-03 10:51
Duplicate of #7

**Closed as completed by xenopeek** 2022-03-03 10:51 UTC

**Comment by kangal3632** [comment] 2022-03-03 17:38
Vincent,

I followed the same steps you took it and the message went away. I didn't
know the issues with Gnome Boxes and reported the error as a bug.
