### ISSUE TITLE
xsession: Source .profile

### ISSUE THREAD

**Issue by vimes666** [linuxmint/lmde-5-cinnamon-beta#5] opened 2022-02-28 23:32 UTC
/home/$USER/bin is not automatically sourced when it exists like in the other mint editions.
I know it did not work in LMDE4 either but maybe this is the moment to fix that?
This issue has come up in the forum several times in the past and was never solved. For reference, the last one [here](https://forums.linuxmint.com/viewtopic.php?p=2140237#p2140237)

**Comment by C8forT** [comment] 2022-03-01 23:37
Specifically, LMDE 5 is not reading ~/.profile in the user's home directory (even when there is not a ~/.bash_profile file nor a ~/.bash_login file).

There is a work-around that can be used until the bug is fixed:  Create a text file named .xsessionrc in the home directory (~/.xsessionrc).  In that file add the following code:

if [ -f ~/.profile ]; then
      . ~/.profile
fi

If getting LMDE to read ~/.profile is problematic (which may be the case since it appears the bug has been around at least since LMDE 4 based on the original post above), maybe the team should just push out an update adding ~/.xsessionrc as a near term solution.

**Comment by orcus-de** [comment] 2022-03-03 16:59
The issue is around since LMDE switched to lightdm with LMDE 3 (where debian uses different compile time defaults with ligthdm and misses 2 config files (being around with ubuntu (based mint)).

if you want to fix lightdm setup -> https://www.orcus.de/main_workarounds/lmde3_fix_profile.htm

**Comment by C8forT** [comment] 2022-03-03 23:40
So, there are at least two ways to work around the bug.  Why doesn't the LMDE team implement one of them?  The solution I posted works and is pretty easy to implement.  Just add one more hidden file to the home directory when LMDE installs.

**Comment by C8forT** [comment] 2022-03-04 00:05
orcus-de I executed the script code at the website - it worked!  So, confirmed, two different solutions are available that both work.  I like your solution better because it results in one less hidden file cluttering up my home directory.  

Do the changes implemented by your script code stay even after an update for LightDM comes through?

**Comment by C8forT** [comment] 2022-03-04 00:26
This bug is not insignificant and should not be ignored.  If for some reason the LMDE team chooses not to implement either of the known solutions to fix the bug in the release, perhaps they should add orcus-de's script code to the welcome screen with instructions on how to run it in the terminal, or maybe add a button user's can select to execute the script code, kind of like the button to install language packs.

**Comment by orcus-de** [comment] 2022-03-04 06:50
yup - the modifications should just keep working with updates - at least they did here for some years.
In the essence its a config file (to override an option which is by default off with debian (on with ubuntu)) and 2 extra files (coming from ubuntu) which drive a) the sourcing of the profile files and b) adding user directories like ~/bin and ~/.local/bin to $PATH if being available (important for snap for example).

**Comment by clefebvre** [comment] 2022-03-09 16:14
Fixed in debian-system-adjustments 2022.03.09.1. Please close the issue if you're able to test the fix.

**Comment by xenopeek** [comment] 2022-03-09 18:41
After installing the update, creating ~/bin and logging out & back in—it is added to $PATH same as on Linux Mint 20.3.

**Closed as completed by xenopeek** 2022-03-09 18:41 UTC
