### ISSUE TITLE
Old Cinnamon bug in main menu persists in LMDE 5

### ISSUE THREAD

**Issue by harlekin777** [linuxmint/lmde-5-cinnamon-beta#39] opened 2022-03-08 15:37 UTC
See https://github.com/linuxmint/cinnamon/issues/10264
It was never fixed.

**Comment by leigh123linux** [comment] 2022-03-08 16:08
Duplicate of  https://github.com/linuxmint/cinnamon/issues/10264

**Closed as completed by leigh123linux** 2022-03-08 16:08 UTC
