### ISSUE TITLE
Not fully translated

### ISSUE THREAD

**Issue by NerdsMaxx** [linuxmint/lmde-5-cinnamon-beta#46] opened 2022-03-10 17:02 UTC
## On Linux Mint 20.3 Una, it's right.
![image](https://user-images.githubusercontent.com/69761459/157756355-b3c47f54-fcd5-42f0-ada0-1c489ffeaa49.png)

## But on LMDE 5, it's not.
![image](https://user-images.githubusercontent.com/69761459/157756279-4dfb3415-d142-4636-95bc-c59d9594d222.png)

**Comment by clefebvre** [comment] 2022-03-11 16:34
OK, I can reproduce.

**Comment by clefebvre** [comment] 2022-03-11 16:44
I see what the problem is... aptdaemon does not ship any translations. In Ubuntu/Mint these are part of the language packs (which is something that doesn't exist in Debian).

A quick solution would be to simply remove the title. It doesn't really add any info anyway.

Long term if we want to keep using aptdaemon (which is discontinued upstream) we probably need to fork it and start developing it ourselves.

I'll add this to the Mint 21 roadmap. It's a wontfix in the meantime.

**Closed as completed by clefebvre** 2022-03-11 16:44 UTC
Labels: bug

**Comment by kelebek333** [comment] 2022-03-11 18:36
If you rebuild this package from source for Elsie, you can solve this issue.
