### ISSUE TITLE
Xed made a beep sound.

### ISSUE THREAD

**Issue by vegam57** [linuxmint/lmde-5-cinnamon-beta#41] opened 2022-03-09 00:40 UTC
Xed made a beep sound.

I've encountered a beep sound while using the LMDE5 Xed three times.
A beep sound was generated by pressing the ↑ key on the first line.
I haven't been able to identify the reproduction procedure.
Restarting Xed doesn't fix it.
Restarting my PC will fix it.
But it may recur.

I haven't encountered it in LM20.3, so I think the cause is something unique to LMDE5.
I haven't been able to identify the reproduction procedure, so please close this report if it's annoying.

**Comment by Jeremy7701** [comment] 2022-03-09 01:00
I can reproduce this in xed in LMDE4 by pressing any arrow key on an empty file.
It's **very faint** (quieter than a mouse click!) as it comes from the internal "beep" speaker in my desktop - not from my external loudspeaker.

I have only tried LMDE5 in a VM, so it doesn't occur there.

**Comment by vegam57** [comment] 2022-03-09 02:02
> It's very faint (quieter than a mouse click!) as it comes from the internal "beep" speaker in my desktop - not from my external loudspeaker.

Hi,
The beep sound on my PC makes my dog jump up :)

**Comment by xenopeek** [comment] 2022-03-09 08:35
Xed is based on Gedit/Pluma and all these use the system bell sound as feedback when you press cursor keys in direction it can't go (when you're at the beginning of the file and press left/up or at the end of the file and press right/down). It's a mellow sound. The default bell sound is /usr/share/sounds/freedesktop/stereo/bell.oga (command `xdg-open /usr/share/sounds/freedesktop/stereo/bell.oga` to play it). For computers with a traditional hardware PC speaker—which I think few computers come with—I guess your system may use that instead for feedback and it may not be as a nice a sound.

But this isn't new in LMDE 5 and not a bug so I'm closing it for this bug squash.

If the sound annoys you, you can disable your hardware PC speaker. Try first if you can reproduce the sound with above suggestion (pressing up/left/down/right in an empty file) and then run the command `sudo modprobe -rv pcspkr` and try again to reproduce it. This should turn off the hardware PC speaker. If that works and you don't want to use your hardware PC speaker (and you don't want to simply unplug it) you can make that permanent by blacklisting the pcspkr driver. Put "blacklist pcspkr" in a file /etc/modprobe.d/pcspkr.conf and after reboot it will remain disabled.

**Closed as completed by xenopeek** 2022-03-09 08:35 UTC

**Comment by vegam57** [comment] 2022-03-09 09:18
Thank you for your kind information.

**Comment by mtwebster** [comment] 2022-03-09 11:22
It sounds like you've enabled event feedback -

Check your accessibility settings, under Keyboard:

![image](https://user-images.githubusercontent.com/262776/157431824-40efa515-01f1-4be0-bd53-bac3a7129d35.png)

See if you have 'audio alerts' enabled.

**Comment by vegam57** [comment] 2022-03-09 19:00
Hi
Thank you for adding the viewpoint.
But the switch has always been off. 

![スクリーンショット 2022-03-10 03-55-05](https://user-images.githubusercontent.com/78515193/157512343-97d65bba-88b4-4cf0-915f-ee161294c364.png)
